// Core browser flow primitive — one local HTTP server, per-flow descriptors.
//
// All browser-driven UX (login, picker, logout) runs through `runBrowserFlow`.
// The primitive owns: server creation, CSRF token generation, CSP/Cache-Control
// headers, AbortSignal wiring, timeout, 404 fallback, and structured logging.
// Each flow supplies only its route table and resolution rule.

import { createServer } from "node:http";
import type { IncomingMessage, ServerResponse, Server } from "node:http";

import type { z } from "zod";

import { logger } from "../logger.js";
import {
  buildLoopbackCsp,
  generateRandomToken,
  validateLoopbackPostHeaders,
  verifyCsrfToken,
} from "./security.js";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface BrowserFlow<Result> {
  /** Short label used in logs (`"login"`, `"picker"`, `"logout"`). */
  readonly name: string;
  /** Build the routes for this flow. Called once after the server binds. */
  readonly routes: (ctx: FlowContext<Result>) => RouteTable;
  /** Per-flow timeout in ms. Defaults to 120_000 (2 minutes). */
  readonly timeoutMs?: number;
}

export interface FlowContext<Result> {
  /** Per-server CSRF token, already generated by the primitive. */
  readonly csrfToken: string;
  /** `["127.0.0.1:<port>", "localhost:<port>"]` for POST Host pinning. */
  readonly allowedHosts: readonly string[];
  /** Resolve the flow's result Promise from inside a handler. */
  readonly resolve: (result: Result) => void;
  /** Reject the flow's result Promise from inside a handler. */
  readonly reject: (err: Error) => void;
  /** The underlying HTTP server (needed by `respondAndClose`). */
  readonly server: Server;
}

export type RouteTable = Readonly<Record<string, RouteHandler>>;

export type RouteHandler = (
  req: IncomingMessage,
  res: ServerResponse,
  /** Per-request CSP nonce, already set on the response. */
  nonce: string,
) => void | Promise<void>;

export interface FlowHandle<Result> {
  /** `http://127.0.0.1:<port>` — pass to openBrowser or surface to the user. */
  readonly url: string;
  /** Resolves with the flow's result, or rejects on timeout / abort / error. */
  readonly result: Promise<Result>;
  /** Close the server early. Idempotent. */
  readonly close: () => void;
}

// ---------------------------------------------------------------------------
// Maximum POST body size (1 MB)
// ---------------------------------------------------------------------------

const MAX_BODY_SIZE = 1_048_576;

// ---------------------------------------------------------------------------
// runBrowserFlow
// ---------------------------------------------------------------------------

export function runBrowserFlow<Result>(
  flow: BrowserFlow<Result>,
  signal: AbortSignal,
): Promise<FlowHandle<Result>> {
  const timeoutMs = flow.timeoutMs ?? 120_000;

  if (signal.aborted) {
    return Promise.reject(
      signal.reason instanceof Error ? signal.reason : new Error("Operation cancelled"),
    );
  }

  return new Promise<FlowHandle<Result>>((resolveHandle, rejectHandle) => {
    const csrfToken = generateRandomToken();
    // Initialized synchronously by the Promise constructor below — safe
    // to reference in the server callback and timer without risk of
    // reading `undefined`.
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    let resultResolve: (result: Result) => void = () => {};
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    let resultReject: (err: Error) => void = () => {};

    const result = new Promise<Result>((resolve, reject) => {
      resultResolve = resolve;
      resultReject = reject;
    });

    let routes: RouteTable | undefined;

    const server = createServer((req, res) => {
      const rawUrl = req.url ?? "/";
      const parsedUrl = new URL(rawUrl, `http://127.0.0.1`);
      const pathname = parsedUrl.pathname;
      const method = req.method ?? "GET";
      const routeKey = `${method} ${pathname}`;

      // Per-request CSP nonce
      const nonce = generateRandomToken();

      res.setHeader("Cache-Control", "no-store, no-cache, must-revalidate");
      res.setHeader("Pragma", "no-cache");
      res.setHeader("Content-Security-Policy", buildLoopbackCsp(nonce));

      const handler = routes?.[routeKey];
      if (handler) {
        void Promise.resolve(handler(req, res, nonce)).catch((err: unknown) => {
          logger.error("browser flow route error", {
            flow: flow.name,
            route: routeKey,
            error: err instanceof Error ? err.message : String(err),
          });
          if (!res.headersSent) {
            res.writeHead(500, { "Content-Type": "text/plain" });
            res.end("Internal Server Error");
          }
        });
      } else {
        res.writeHead(404, { "Content-Type": "text/plain" });
        res.end("Not Found");
      }
    });

    // Abort signal handling
    const onAbort = (): void => {
      logger.info("browser flow aborted", { flow: flow.name });
      server.close();
      resultReject(
        signal.reason instanceof Error ? signal.reason : new Error("Operation cancelled"),
      );
    };
    signal.addEventListener("abort", onAbort, { once: true });

    server.listen(0, "127.0.0.1", () => {
      const addr = server.address();
      if (!addr || typeof addr === "string" || !addr.port) {
        server.close();
        rejectHandle(new Error("Failed to get server address"));
        return;
      }
      const port = String(addr.port);
      const allowedHosts = [`127.0.0.1:${port}`, `localhost:${port}`];
      const url = `http://127.0.0.1:${port}`;

      const ctx: FlowContext<Result> = {
        csrfToken,
        allowedHosts,
        resolve: resultResolve,
        reject: resultReject,
        server,
      };

      routes = flow.routes(ctx);

      logger.info("browser flow started", { flow: flow.name, url });

      const close = (): void => {
        server.close();
      };

      resolveHandle({ url, result, close });
    });

    server.on("error", (err) => {
      logger.error("browser flow server error", { flow: flow.name, error: err.message });
      rejectHandle(err);
    });

    const timer = setTimeout(() => {
      logger.warn("browser flow timed out", { flow: flow.name });
      server.close();
      resultReject(
        new Error(
          flow.name === "picker"
            ? "Selection timed out - no choice made within the time limit. Please try again."
            : flow.name === "logout"
              ? "Logout confirmation timed out"
              : `Browser flow "${flow.name}" timed out`,
        ),
      );
    }, timeoutMs);

    server.on("close", () => {
      clearTimeout(timer);
      signal.removeEventListener("abort", onAbort);
    });
  });
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Serve an HTML response with 200 OK. */
export function serveHtml(res: ServerResponse, html: string): void {
  res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
  res.end(html);
}

/**
 * Read a JSON POST body (≤1 MB), validate headers + CSRF + a zod schema,
 * then invoke `onValid`. Each failure responds with the appropriate status.
 */
export function readJsonWithCsrf<S extends z.ZodType, R>(
  req: IncomingMessage,
  res: ServerResponse,
  ctx: FlowContext<R>,
  schema: S,
  onValid: (data: z.infer<S>) => void | Promise<void>,
): void {
  const headerCheck = validateLoopbackPostHeaders(req, {
    allowedHosts: ctx.allowedHosts as string[],
  });
  if (!headerCheck.ok) {
    res.writeHead(headerCheck.status, { "Content-Type": "text/plain" });
    res.end(headerCheck.message);
    return;
  }

  let body = "";
  let size = 0;
  req.on("data", (chunk: Buffer) => {
    size += chunk.length;
    if (size > MAX_BODY_SIZE) {
      res.writeHead(413, { "Content-Type": "text/plain" });
      res.end("Payload Too Large");
      req.destroy();
      return;
    }
    body += chunk.toString();
  });
  req.on("end", () => {
    let parsed: unknown;
    try {
      parsed = JSON.parse(body);
    } catch {
      res.writeHead(400, { "Content-Type": "text/plain" });
      res.end("Invalid request body");
      return;
    }

    const parseResult = (schema as z.ZodType).safeParse(parsed);
    if (!parseResult.success) {
      res.writeHead(400, { "Content-Type": "text/plain" });
      res.end("Invalid request body");
      return;
    }

    // Verify CSRF token — it must be present as `csrfToken` in the parsed body
    const data = parseResult.data as Record<string, unknown>;
    if (!verifyCsrfToken(ctx.csrfToken, data["csrfToken"])) {
      res.writeHead(403, { "Content-Type": "text/plain" });
      res.end("Forbidden: invalid CSRF token");
      return;
    }

    void Promise.resolve(onValid(parseResult.data as z.infer<S>)).catch((err: unknown) => {
      if (!res.headersSent) {
        const message = err instanceof Error ? err.message : String(err);
        logger.error("browser flow onValid error", { error: message });
        res.writeHead(500, { "Content-Type": "text/plain" });
        res.end(`Error: ${message}`);
      }
    });
  });
}

/** Write a 200 JSON response then close the server after a 100 ms flush delay. */
export function respondAndClose(res: ServerResponse, server: Server, body: unknown): void {
  res.writeHead(200, { "Content-Type": "application/json" });
  res.end(JSON.stringify(body));
  setTimeout(() => {
    server.close();
  }, 100);
}
