// Reads SVG files from assets/ and generates src/templates/icons.ts
// with base64-encoded SVG data URIs.
//
// Usage:
//   `npm run icons`          # write icons.ts
//   `npm run icons` --check  # verify icons.ts is up-to-date (exit 1 if stale)

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const assetsDir = resolve(root, "assets");
const outFile = resolve(root, "src", "templates", "icons.ts");

/** Read an SVG file and return a data URI string. */
function svgToDataUri(filename) {
  const svg = readFileSync(resolve(assetsDir, filename), "utf-8");
  const b64 = Buffer.from(svg).toString("base64");
  return `data:image/svg+xml;base64,${b64}`;
}

function generate() {
  const symbolDataUri = svgToDataUri("symbol.svg");
  const symbolDarkDataUri = svgToDataUri("symbol-dark.svg");
  const symbolLightDataUri = svgToDataUri("symbol-light.svg");
  const logoDataUri = svgToDataUri("logo.svg");
  const logoDarkDataUri = svgToDataUri("logo-dark.svg");
  const logoLightDataUri = svgToDataUri("logo-light.svg");

  return `// SVG icon data URIs for embedding in served HTML.
// Generated by scripts/encode-icons.mjs — do not edit manually.
// To regenerate: npm run icons

// ---------------------------------------------------------------------------
// Symbols (compact mark — used for favicons)
// ---------------------------------------------------------------------------

/** Brand purple symbol as SVG data URI — used as favicon. */
export const symbolDataUri =
  "${symbolDataUri}";

/** Dark symbol as SVG data URI — for use on light backgrounds. */
export const symbolDarkDataUri =
  "${symbolDarkDataUri}";

/** Light symbol as SVG data URI — for use on dark backgrounds. */
export const symbolLightDataUri =
  "${symbolLightDataUri}";

// ---------------------------------------------------------------------------
// Logos (full wordmark — used as page icon in browser UI)
// ---------------------------------------------------------------------------

/** Brand purple logo as SVG data URI. */
export const logoDataUri =
  "${logoDataUri}";

/** Dark logo as SVG data URI — for use on light backgrounds. */
export const logoDarkDataUri =
  "${logoDarkDataUri}";

/** Light logo as SVG data URI — for use on dark backgrounds. */
export const logoLightDataUri =
  "${logoLightDataUri}";
`;
}

const checkMode = process.argv.includes("--check");
const expected = generate();

if (checkMode) {
  let current;
  try {
    current = readFileSync(outFile, "utf-8");
  } catch {
    console.error("icons.ts does not exist. Run: npm run icons");
    process.exit(1);
  }
  if (current !== expected) {
    console.error("icons.ts is out of date with SVG assets. Run: npm run icons");
    process.exit(1);
  }
  console.log("icons.ts is up to date.");
} else {
  writeFileSync(outFile, expected, "utf-8");
  console.log(`Generated ${outFile}`);
}
